export default {
  namespaced: true,
  getters: {
    data: state => state.data,
    filters: state => state.filters,
    filteredData: state => state.filteredData,
    recentProjects: state => state.recentProjects,
  },
  mutations: {
    reset(state) {
      // Map all projects -> gather all tags of each project
      if (!state.init) {
        state.data.forEach(item => {
          item.tags = [];
          item.tags.push(...item.roles, ...item.stack);
          if (item.startup) { item.tags.push('STARTUP | FROM SCRATCH'); }
        });
        state.init = true;
      }

      // Here filtering happens
      if (state.filters.length > 0) {
        let result = state.data;
        state.filters.forEach(filter => {
          result = result.filter(function(project) {
            let projectLowercase = project.tags.toString().toLowerCase();
            return projectLowercase.indexOf(filter.toLowerCase()) > -1;
          });
          state.filteredData = result;
        });
      } else {
        state.filteredData = state.data;
      }
    },
    pushTag(state, tag) {
      if (!state.filters.includes(tag)) {
        state.filters.push(tag);
      }
    },
    removeTag(state, tag) {
      state.filters = state.filters.filter(item => item !== tag);
    },
    filterPurge(state) {
      state.filters = [];
    },
  },
  state: {
    init: false,
    filters: [],
    filteredData: [],
    data: [
      {
          title: "Front-end developers mentoring",
          tasks: [
            'Studying plan development',
            'Mentoring and Tutoring',
          ],
          startup: true,
          images: [],
          description: "Successfully raised 2 frontend-developers from 0 that are now qualified employed specialists, building their careers in web-development industry",
          roles: ['Mentor', 'tutor'],
          stack: ['Figma', 'Github', 'Github pages'],
          from: null,
          to: null,
          year: 2021,
          duration: '2 years',
          tags: [],
      },
      {
          title: "Saas solution for crafters",
          url: null,
          tasks: [
              'Prototyping and implementing from scratch',
              'Teamleading, code review',
              'Database and API (+JSON API) development',
              'Deploy & server management',
          ],
          roles: ['App architect', 'Teamlead', 'Fullstack', 'PM', 'DevOps'],
          stack: [],
          startup: true,
          images: [],
          description: null,
          from: null,
          to: null,
          year: 2022,
          duration: '1 year',
          tags: [],
      },
      {
          title: "Statistic/Interactive widget app for casino gaming streamers",
          url: 'https://slotsstreaming.pro/lp',
          tasks: [
              'Prototyping and implementing from scratch',
              'Teamleading, code review',
              'Database and API (+JSON API) development',
              'Deploy & server management',
          ],
          roles: ['App architect', 'Teamlead', 'Fullstack', 'PM', 'DevOps'],
          stack: [],
          startup: true,
          images: [],
          description: null,
          from: null,
          to: null,
          year: 2022,
          duration: '1 year',
          tags: [],
      },
      {
          title: 'Photobooth media management SaaS constructor for event-agencies',
          url: 'https://www.eventkite.co/',
          tasks: [
            "Prototyping and implementing from scratch",
            "Teamleading",
            "Database and API (+JSON API) development",
            "Vendor API consumation, XML parsing, media processing",
            "Rich dashboard UI implementation",
            "Deploy & server management",
          ],
          roles: ["Fullstack", "Teamlead", "Application architect", "DevOps"],
          stack: [],
          startup: true,
          images: [],
          description: null,
          from: null,
          to: null,
          year: 2021,
          duration: '1.5 years',
          tags: [],
      },
      {
          title: 'Social networks scheduled posting saas app',
          url: null, // TODO
          tasks: [
            "Server management & queue management",
            "Support / Bugfixing",
            "API integration fixing (twitter)",
            "Queue and server management",
          ],
          stack: ['Laravel', 'VueJS2', 'VuePrime UI KIT', 'MySQL', 'Redis', 'Horizon', 'Supervisor', 'Docker', 'ServerPilot', 'Figma'],
          roles: ['Fullstack', 'Devops'],
          startup: false,
          images: [],
          description: null,
          from: null,
          to: null,
          year: 2022,
          duration: 'few months',
          tags: [],
      },
      {
        title: 'Countryside mobile navigator app',
        url: null,
        tasks: [
          'Prototyping and implementing from scratch',
          'Teamleading',
          'Database and API (+JSON API) development',
          'Public UI',
          'Customer (venue) dashboard UI',
          'Admin UI',
          'GoogleMaps API integration, marker clusters',
          'HTML GPS research & integration',
          'PWA -> gonative.io & Apple and Google markets management',
        ],
        roles: ['Laravel', 'Laravel8', 'VueJS2', 'VuePrime UI KIT', 'MySQL', 'Redis', 'Horizon', 'Supervisor', 'Docker', 'ServerPilot', 'Figma'],
        stack: [],
        startup: true,
        images: [],
        description: null,
        from: null,
        to: null,
        year: 2022,
        duration: '4 months',
        tags: [],
      },
      {
        title: 'Nightclubs search & book mobile app',
        url: 'https://www.partyr.com.au/',
        tasks: [
          "Prototyping and implementing from scratch",
          "Teamleading",
          "Database and API (+JSON API) development",
          "Public UI",
          "Customer (venue) dashboard UI",
          "Admin UI",
          "GoogleMaps API integration, marker clusters, googlemaps venues parsing",
          "HTML GPS integration",
          "PWA -> gonotive.io & Apple and Google markets management",
        ],
        images: [],
        description: null,
        startup: true,
        stack: ['Laravel', 'VueJS2', 'VuePrime UI KIT', 'MySQL', 'Redis', 'Horizon', 'Supervisor', 'Docker', 'ServerPilot', 'Figma'],
        roles: ['Fullstack', 'Teamlead', 'Application architect', 'DevOps'],
        from: null,
        to: null,
        year: 2021,
        duration: '6 months',
        tags: [],
      },
      {
        title: 'Discount aggregator app',
        url: 'https://cartame.by/',
        tasks: [
          'developing v2 api for mobile application',
          'migrating database, merging user databases, providing consistancy of users meta-data and related entities',
          'servers management',
          'authentication flows refactoring',
        ],
        images: [],
        description: null,
        startup: false,
        stack: ['laravel', 'Laravel6', 'PHP', 'PHP7', 'mysql', 'docker', 'nginx', 'git', 'gitlab', 'ubuntu'],
        roles: ['devops', 'backend'],
        from: null,
        to: null,
        year: 2021,
        duration: '2 months',
        tags: [],
      },
      {
        title: 'Green travel ticket service',
        url: null,
        tasks: [
          'Application & database architecture',
          'Teamleading, code review',
          'Ticket vendors integrations',
          'Internal unification of data and processes',
          'Amazon AWS, EC2, RDS server administration',
        ],
        images: [],
        description: null,
        startup: true,
        stack: ['laravel', 'Laravel6', 'PHP', 'PHP7', 'mysql', 'redis', 'docker', 'nginx', 'aws', 'composer', 'git', 'bitbucket', 'bitbucket pipelines'],
        roles: ['pm', 'devops', 'backend', 'teamlead'],
        from: '07.2020',
        to: '12.2020',
        year: 2020,
        duration: '5 months',
        tags: [],
      },
      {
        title: 'Multilingual content creation agency',
        url: 'https://greatcontent.com',
        tasks: [
          'Backend & Frontend: support, bugfixing, new functionality developing',
          'Frontend: brand new customer interface on VueJS from scratch',
        ],
        images: [],
        description: null,
        startup: false,
        stack: ['Symfony', 'Symfony3', 'PHP', 'PHP7', 'MySQL', 'VueJS', 'vuex', 'mdbootstrap', 'flex', 'webpack', 'nginx', 'jenkins', 'composer', 'git', 'Gitlab'],
        roles: ['backend', 'frontend', 'fullstack'],
        from: '12.2019',
        to: '07.2020',
        year: 2020,
        duration: '0.5 year',
        tags: [],
      },
      {
        title: 'Business system for real estate booking',
        url: null,
        tasks: [
          'Project & database developing',
          'Custom Node Tree-inheritance for Eloquent ORM development',
          'Gitlab composer packages development',
          'Lesser docker config modifications',
          'MJML Email templating and localization',
          'Code reviewing in pair programming',
          'PHPUnit Tests covering',
          'Cross-stack Authentication',
          'JsonApi Developing',
        ],
        images: [],
        description: 'Designed to manually create bookings of different types as well as process incoming ones. Designed to be used by various authorized real-estate organizations.',
        startup: true,
        stack: ['laravel', 'laravel5', 'php', 'php7', 'git', 'gitlab', 'phpunit', 'composer'],
        roles: ['backend'],
        from: '10.2018',
        to: '07.2019',
        year: 2018,
        duration: '1 year',
        tags: [],
      },
      {
        title: 'Internship platform',
        url: 'https://doorofclubs.com/',
        tasks: [
          'Improved: Laravel Forge CI scripts',
          'Supported: Refactoring legacy code. Moving business-logic from controllers to appropriate responsibility layers',
          'Improved/Supported: Frontend pages/modules',
          'Improved: Vue-flow. To single-module-files (.Vue) from multi-modules-file(.js)',
          'Implemented: Whole project companies analytics calculation, with xls-importing and displaying it on “vue-routed” SPA in company dashboard tab',
          'Implemented: Data export flow from text-search service called “Algolia” to internal db',
          'Implemented: Complicated “Diversity” students filtering',
          'Code Reviewing',
          'Bugfixing',
        ],
        images: [],
        description: 'Service for companies to send and manage internships and job offers service to widely-searchable pool of talented students.',
        startup: false,
        stack: ['laravel', 'laravel5', 'php', 'php7', 'vuejs', 'git', 'github', 'aws', 'algolia'],
        roles: ['backend', 'frontend', 'fullstack'],
        from: '04.2018',
        to: '07.2018',
        year: 2018,
        duration: '3 months',
        tags: [],
      },
      {
        title: 'Travel ticket service with social network features',
        url: null,
        tasks: [
          'Creating project & application architecture',
          'Development tasks formulation/assignment/tracking',
          'Code reviewing',
          'France railroad monopolist API integration (Routes, Booking)',
          'API routes caching',
          'Composing route-search results from API Routes and Application groups with group detalizaion',
          'Ticket ordering system with availability of booking 1 and more tickets & booking for another persons(s) where booker is not going',
          'User invitation system',
          'Access control lists - who and when can view group-lists and other users profiles',
          'Stripe payment gateway integration (delayed charging(“freezing funds”), charge capturing, refunding)',
          'Background tasks implementing (emailing jobs daemonizing, time-based group events background handling)',
          '3rd party integrations (FB, MailChimp, Mailgun)',
          'Rich system of events that leads to user email-notifying',
          'Rich administrative dashboard',
          'Localization (FR/EN) backend + frontend',
          'User account management (avatars, details, FB account data pulling, etc.)',
          'Tests covering',
          'Stage server supporting & production deployment',
        ],
        images: [],
        description: 'Booking system for group train travel with social network features. Allows users to cooperate into group to book a group ticket which is significantly cheaper than if each member would book single ticket. System integrated with transport vendor routes and tickets API, payment system, email-advertising system, OAuth2 FaceBook API and email service. Teamleading: codereview, task defenition, assignment and control',
        startup: true,
        stack: ['laravel', 'laravel5', 'php', 'php7', 'git', 'bitbucket'],
        roles: ['backend'],
        from: '01.2018',
        to: '04.2018',
        year: 2018,
        duration: '3 months',
        tags: [],
      },
      {
        title: 'Telemedicine service',
        // url: 'https://doconline.lv/en/home', TODO WEBARCHIVE
        url: 'null',
        tasks: [
          'Application & database architecture development',
          'RESTful API development',
          'Integration with FireBase, TokBox, SMS gateway, Payment gateway',
          'Unit, Functional testing / bug fixing',
          'Production deployment on AWS',
          'Product launch and supporting'
        ],
        images: [
        ],
        description: 'Allows to find doctors and make online video consultations with them. System was integrated with the video streaming service, payment service. Implemented sms, email, push notifications. Integration with mobile applications was implemented. Teamleading: codereview, task defenition, assignment and control',
        startup: true,
        stack: ['symfony', 'symfony2', 'php', 'php7', 'git', 'bitbucket', 'jira', 'aws'],
        roles: ['backend'],
        from: '03.2017',
        to: '01.2018',
        year: 2017,
        duration: '1 year',
        tags: [],
      },
      {
        title: 'Online catalog for lighting devices retailer',
        url: null,
        tasks: [
          'Symfony establishment',
          'User roles and privileges segmentation',
          'Administrative functionality',
          'Twig templating',
          'History functionality',
          'Rich editing functionality',
          'CSV export/import functionality',
        ],
        images: [],
        description: null,
        startup: true,
        stack: ['symfony2', 'php', 'php5', 'html', 'css', 'js', 'bootstrap', 'git', 'bitbucket'],
        roles: ['backend', 'frontend'],
        from: '01.2016',
        to: '03.2016',
        year: 2017,
        duration: '3 months',
        tags: [],
      },
      {
        title: 'Wordpress custom plugin',
        // TODO REPLACE DATES - DATES ARE WRONG
        url: 'https://www.loom.com/share/369b51b2d292466497cf4d64f7cc8b02',
        tasks: [
          'Custom WordPress plugin development',
          'Developing VueJS application with reactive color-picking, and managing customizable sets of items of different types',
          'Integration with other plugins: WordPress Contact Form 7, Flamingo emails manager',
          'Responsive templating with flexbox',
          'BE/FE validation',
          'Database integration',
        ],
        images: [],
        description: null,
        startup: true,
        stack: ['wordpress', 'php', 'php5', 'html', 'css', 'js', 'vueJs', 'npm', 'webpack', 'flexbox', 'mercurial', 'bitbucket'],
        roles: ['frontend', 'backend'],
        from: '12.2015',
        to: '01.2016',
        year: 2017,
        duration: '3 months',
        tags: [],
      },
      {
        title: 'Personal blog for dog-trainer',
        url: 'http://shap-dog-training.by',
        tasks: [
          'Wordpress theme install',
          'HTML templating & CSS styling',
          'Youtube channel and content management',
        ],
        images: [],
        description: null,
        startup: true,
        stack: ['wordpress', 'html', 'css'],
        roles: ['frontend'],
        from: '08.2015', // TODO REFACTOR
        to: '09.2015',   // TODO REFACTOR
        year: 2017,
        duration: "2 weeks",
        tags: [],
      },
      {
        title: 'Email-marketing automation for restaurant business',
        url: null,
        tasks: [
          'Database and project architecture development',
          'Synchronization between Resdiary restaurant booking-service and Application via REST API',
          'Synchronization between Application and ActiveCampaign marketing service via REST API',
          'Symfony CLI commands',
        ],
        images: [],
        description: null,
        startup: true,
        stack: ['symfony', 'symfony2', 'php', 'php5', 'git', 'bitbucket'],
        roles: ['backend'],
        from: '11.2016',
        to: '01.2017',
        year: 2016,
        duration: '2 months',
        tags: [],
      },
      {
        title: 'Backoffice Admin web-service for managing certification courses',
        url: 'https://biiab.co.uk/',
        tasks: [
          'SOAP API bulk-data synchronization',
          'Database architecture',
          'User roles and privileges segmentation',
          'CSV export/import functionality',
          'Developing RESTful API, documented with APIDoc',
          'Rich editing functionality',
          'History logging functionality',
          'Symfony2 CLI commands',
          'Social networks API integration: Twitter, Facebook',
          'Twig templating',
        ],
        images: [],
        description: null,
        startup: true,
        stack: ['symfony', 'symfony2', 'php', 'php5', 'html', 'css', 'js', 'bootstrap', 'git', 'bitbucket'],
        roles: ['backend', 'frontend'],
        from: '05.2016',
        to: '11.2016',
        year: 2016,
        duration: '3 months',
        tags: [],
      },

      {
        title: 'Landing Page for construction goods',
        url: null,
        tasks: [
          'PSD slicing',
          'Templating',
        ],
        images: [],
        description: null,
        startup: true,
        stack: ['html', 'css', 'js', 'jquery', 'bootstrap'],
        roles: ['frontend'],
        from: '08.2015', // TODO REFACTOR
        to: '08.2015',   // TODO REFACTOR
        year: 2016,
        duration: "1 week",
        tags: [],
      },
      {
        title: 'SEO | UX optimization projects',
        url: null,
        tasks: [
          'Micro-markup templates injections',
          'SEO-valid HTML markups',
          'CMS Seo-modules searching/installing/customization',
          'Managing robots.txt, sitemap.xml',
          'Lesser designs customizations, mostly: user feedback | forms/modals | breadcrumbs | online customers support js-plugins',
        ],
        images: [],
        description: null,
        startup: false,
        stack: ['php', 'php5', 'wordpress', 'joomla', 'html', 'css', 'js'],
        roles: ['frontend', 'backend'],
        from: '06.2015', // TODO REFACTOR
        to: '08.2015',   // TODO REFACTOR
        year: 2016,
        duration: "2 weeks",
        tags: [],
      },
      {
        title: 'Autoparts online-shop mobile redesign',
        url: null,
        tasks: [
          'Injecting responsive bootstrap grid into ugly written codeigniter 2 templates',
          'Achieved experience with legacy templates : no code-style and over 7 nesting php-conditions levels',
          'Frontend redesign',
        ],
        images: [],
        description: null,
        startup: false,
        stack: ['html', 'css', 'js', 'jquery', 'bootstrap', 'Codeigniter 2', 'git', 'bitbucket'],
        roles: ['frontend', 'designer'],
        from: '04.2015', // TODO REFACTOR
        to: '06.2015',   // TODO REFACTOR
        year: 2016,
        duration: "4 months",
        tags: [],
      },
      {
        title: 'Custom MVC engine',
        url: null,
        tasks: [
          'Kernel establishment',
          'MVC architecture implementation',
          'Custom modules support',
          'Classes Autoloading',
          'Routing system',
          'Front controller system',
          'Output buffering & HTTP Headers management',
          'View-layer inheritance architecture',
          'Functional for delegating managing CSS/JS files from template to view layer',
          'Rendering functionality',
          'Wrapper for CRUD operations as abstraction over database layer implemented',
        ],
        images: [],
        description: null,
        startup: true,
        stack: ['php5', 'html', 'css', 'js', 'bootstrap', 'git', 'bitbucket'],
        roles: ['backend'],
        from: '12.2014', // TODO REFACTOR
        to: '04.2015',   // TODO REFACTOR
        year: 2016,
        duration: '2 months',
        tags: [],
      },
      {
        title: 'Homepage templating | Software for crafting',
        url: 'http://chudibeads.com',
        tasks: [
          'Creating AIDA marketing model for page structure',
          'Html templating and CSS styling from the scratch',
          'Lesser integration of LP into Drupal views system',
        ],
        images: [],
        description: null,
        startup: false,
        stack: ['html', 'css', 'js', 'bootstrap'],
        roles: ['frontend', 'designer'],
        from: '11.2014',
        to: '12.2014',
        year: 2016,
        duration: '2 weeks',
        tags: [],
      },
    ],
    recentProjects: [
      {
        title: 'Photobooth media management SaaS constructor for event-agencies',
        url: 'https://www.eventkite.co/',
        tasks: [
          "Prototyping and implementing from scratch",
          "Teamleading",
          "Database and API (+JSON API) development",
          'Propriatary Breeze API consumation and integration (Breeze is a well-established software for event mediafiles capturing)',
          "Rich dashboard UI and public pages implementation, templating",
          "Deploy & server management",
        ],
        roles: ["Fullstack", "Teamlead", "Application architect", "DevOps"],
        stack: ['Laravel', 'PHP', 'VueJS', 'MySQL', 'Redis'],
        startup: true,
        images: [
            'kites/kites_in_computer_from_lp.png',
            'kites/billing.png',
            'kites/detail_qr.png',
            'kites/qr4x.jpg',
        ],
        description: 'Developed a groundbreaking B2B product tailored for photobooth and photozone owners, such as event studios. Took ownership of the backend development from scratch, leading a 2-developer team by overseeing the frontend developer. The product comprises three main components: administration, customer, and visitor parts. The administration part serves as a comprehensive dashboard for data management. The customer part is the most intricate, offering a wide range of features. Customers can effortlessly modify events and their settings, manage project assignments, moderate data, and customize public page views. Visitors can access the public pages, which are specifically tailored and provided by our product\'s customers, the studios. Our Eventkite product seamlessly integrates with Breeze proprietary software, a \'close-to-hardware\' solution. Studios install Breeze software on iPads and Windows machines, along with DSLR cameras, for media capturing. Eventkite effectively handles media file upload, processing, storage, and delivery to the end-user. During this project, I enhanced my skills in Redis and queue management, utilizing cron and Laravel Horizon for efficient task scheduling and background processing.',
        from: null,
        to: null,
        year: 2021,
        duration: '1.5 years',
        tags: [],
      },
      {
        title: 'Travel ticket service with social network features',
        url: 'https://fingers-media.com/portfolio/trainpool',
        tasks: [
          'Creating project & application architecture',
          'Development tasks formulation/assignment/tracking',
          'Code reviewing',
          'France railroad monopolist API integration (Routes, Booking)',
          'API routes caching',
          'Composing route-search results from API Routes and Application groups with group detalizaion',
          'Ticket ordering system with availability of booking 1 and more tickets & booking for another persons(s) where booker is not going',
          'User invitation system',
          'Access control lists - who and when can view group-lists and other users profiles',
          'Stripe payment gateway integration (delayed charging(“freezing funds”), charge capturing, refunding)',
          'Background tasks implementing (emailing jobs daemonizing, time-based group events background handling)',
          '3rd party integrations (FB, MailChimp, Mailgun)',
          'Rich system of events that leads to user email-notifying',
          'Rich administrative dashboard',
          'Localization (FR/EN) backend + frontend',
          'User account management (avatars, details, FB account data pulling, etc.)',
          'Tests covering',
          'Stage server supporting & production deployment',
        ],
        images: [
            'trainpool/1.png',
            'trainpool/2.png',
            'trainpool/3.png',
            'trainpool/4.png',
            'trainpool/5.png',
            'trainpool/6.png',
            'trainpool/7.png',
            'trainpool/8.png',
            'trainpool/9.png',
            'trainpool/10.png',
            'trainpool/11.png',
        ],
        description: 'Engaged in the most impactful project of my career, where my frontend colleague and I developed an impressive and seamlessly functioning MVP within a span of 2.5 months. In this project, I primarily focused on backend development. During the pre-release phase, I had the privilege of direct communication with the product owners, who visited our office in Minsk, Belarus, originating from France. These face-to-face interactions proved invaluable as we delved into the intricate details of user flow, domain logic, statistics collection, and the implementation of necessary cron jobs. Regrettably, despite our remarkable progress, the product never made it to the market. The project was centered around a social network designed to provide users with more affordable train tickets through the trainpool initiative, which was developed for the French railroad SNCF. Unfortunately, internal issues and strikes stemming from political actions taken by the French government hindered its launch. For further information about the product, please visit this link: https://fingers-media.com/portfolio/trainpool',
        startup: true,
        stack: ['laravel', 'laravel5', 'php', 'php7', 'git', 'bitbucket'],
        roles: ['backend', 'teamlead'],
        from: '01.2018',
        to: '04.2018',
        year: 2018,
        duration: '3 months',
        tags: [],
      },
      {
        title: "Statistic/Interactive widget app for casino gaming streamers",
        url: 'https://slotsstreaming.pro/lp-eng',
        tasks: [
          'Prototyping and implementing from scratch',
          'Teamleading, code review',
          'Database and API (+JSON API) development',
          'Deploy & server management',
        ],
        roles: ['App architect', 'Teamlead', 'Fullstack', 'PM', 'DevOps'],
        stack: ['Laravel', 'PHP', 'VueJS', 'MySQL'],
        startup: true,
        images: [
          'slots/1.png',
          'slots/2.png',
          'slots/3.png',
        ],
        description: 'Served as a team lead and backend developer for a product aimed at delivering real-time game statistics to streamers (e.g., Twitch) based on data collected throughout their usage of the service. The product consisted of two main components: a data collection part facilitated through user interface inputs, and widgets designed for screen capture using OBS or similar programs. This service provided valuable insights and statistics to streamers, enhancing their streaming experience and engagement with their audience.',
        from: null,
        to: null,
        year: 2022,
        duration: '1 year',
        tags: [],
      },
      {
        title: 'Countryside mobile navigator app',
        url: null,
        tasks: [
          'Prototyping and implementing from scratch',
          'Teamleading',
          'Database and API (+JSON API) development',
          'Public UI',
          'Customer (venue) dashboard UI',
          'Admin UI',
          'GoogleMaps API integration, marker clusters',
          'HTML5 GPS research & integration',
          'PWA -> gonative.io & Apple and Google markets management',
        ],
        roles: ['Backend', 'Frontend', 'Fullstack', 'Teamlead', 'DevOps'],
        stack: ['Laravel', 'Laravel8', 'VueJS2', 'VuePrime UI KIT', 'MySQL', 'Redis', 'Horizon', 'Supervisor', 'Docker', 'ServerPilot', 'Figma'],
        startup: true,
        images: [
            'dyk/route_default2x.png',
            'dyk/route_altered2x.png',
            'dyk/route_active2x.png',
            'dyk/route_preview2x.png',
            'dyk/saved_trips2x.png',
            'dyk/search_initial.png',
            'dyk/sign_in2x.png',
            'dyk/Menu2x.png',
            'dyk/map.png',
            'dyk/main.png',
        ],
        description: 'Led the development of an Web/iOS/Android app product. App enables users to effortlessly travel from point A to point B while curating their route by incorporating suggested places of interest, managed by the admin. Once the route is initiated, GPS-triggered audio guides provide real-time guidance. Overcoming challenges with HTML5 GPS integration, we navigated through the SPA->PWA->gonative.io->binary to marketplaces solution. For future GPS-dependent app projects, I recommend considering React Native as a cost-effective alternative to fully native development, as it seamlessly interacts with the mobile device\'s native GPS API. This project also involved the implementation of a custom snap-to-grid feature and a real-time GPS solution. As the full-stack developer and team lead, working on this project was a joyful and inspiring experience.',
        from: null,
        to: null,
        year: 2022,
        duration: '4 months',
        tags: [],
      },
      {
        title: 'Nightclubs search & book mobile app',
        url: 'https://www.partyr.com.au/',
        tasks: [
          "Prototyping and implementing from scratch",
          "Teamleading",
          "Database and API (+JSON API) development",
          "Public UI",
          "Customer (venue) dashboard UI",
          "Admin UI",
          "GoogleMaps API integration, marker clusters, googlemaps venues parsing",
          "HTML GPS integration",
          "PWA -> gonotive.io & Apple and Google markets management",
        ],
        images: [
            'partyr/1.png',
            'partyr/2.png',
            'partyr/3.png',
            'partyr/check_in_success.png',
            'partyr/history.png',
            'partyr/map.png',
            'partyr/onboarding_1.png',
            'partyr/onboarding_2.png',
            'partyr/onboarding_3.png',
            'partyr/review_&_rating.png',
            'partyr/type_of_partying.png',
            'partyr/venue.png',
        ],
        description: 'Led the development of a web, iOS, and Android app powered by Google Maps. The app aimed to enhance people\'s nightlife experiences by providing a convenient platform to search for and book tickets to various music venues in Melbourne, including nightclubs, bars, and restaurants. Users benefited from features such as access to median drink prices, musical genres, favorite places, and distance filtering. Throughout the project, I had the opportunity to explore the conversion of a Single Page Application into a Progressive Web Application and simplified mobile app deployment using gonative.io. As a full-stack developer and team lead, it was a rewarding experience working on an app that aimed to improve people\'s routine in finding enjoyable music-filled nights.',
        startup: true,
        roles: ['Backend', 'Frontend', 'Fullstack', 'Teamlead', 'Application architect', 'DevOps'],
        stack: ['Laravel', 'VueJS2', 'VuePrime UI KIT', 'MySQL', 'Redis', 'Horizon', 'Supervisor', 'Docker', 'ServerPilot', 'Figma'],
        from: null,
        to: null,
        year: 2021,
        duration: '6 months',
        tags: [],
      },
      {
        title: 'Multilingual content creation agency',
        url: 'https://greatcontent.com',
        tasks: [
          'Backend & Frontend: support, bugfixing, new functionality developing',
          'Migrating backend to Symfony 3 from Symfony 1',
          'Migrating to SPA + REST JSON API from monolyth',
          'Backend development and legacy support / bugfixing',
          'Frontend: brand new customer interface on VueJS from scratch',
        ],
        images: [
            'gc/1.png',
            'gc/2.png',
            'gc/3.png',
            'gc/4.png',
            'gc/5.png',
        ],
        description: "Contributed to a well-established product with over 10 years of market presence. Initially joining as a backend developer within a 10+ member team, my responsibilities involved providing support and addressing bug fixes in the existing codebase. We had a greatest CTO here, Oleksii Dubinin appointed us to different parts of app, so we better understarstand whole domain logic, which was pretty rich on features and flows. Later, took a part in migrating product to API+SPA from monolith. This transition allowed for greater scalability and flexibility. Working in a co-programming mode alongside a colleague, we collaborated on the initial frontend development using Vue.js, focusing on designing the architecture, implementing dynamic layouts, and managing routing, store modules. Great experience, great team, GreatContent - big thanks! (hee-hee). My sincere gratitude goes to everyone involved.",
        startup: false,
        roles: ['Backend', 'Frontend', 'Fullstack'],
        stack: ['Symfony', 'Symfony3', 'PHP', 'PHP7', 'MySQL', 'VueJS', 'vuex', 'mdbootstrap', 'flex', 'webpack', 'nginx', 'jenkins', 'composer', 'git', 'Gitlab'],
        from: '12.2019',
        to: '07.2020',
        year: 2020,
        duration: '0.5 year',
        tags: [],
      },
    ]
  },
};
